server:
  port: 8081
spring:
  application:
    name: service-provider
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/1905?characterEncoding=utf8&useSSL=true&serverTimezone=UTC&zeroDateTimeBehavior=CONVERT_TO_NULL
    username: root
    password: root
mybatis:
  type-aliases-package: com.jk.model
  mapper-locations: classpath:mapping/mapper/*.xml
  config-location: classpath:mapping/confg.xml
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8080/eureka/
    instance:
      lease-renewal-interval-in-seconds: 1
      lease-expiration-duration-in-seconds: 2




